### ISSUE TITLE
Comment Arrow Greyed out

### ISSUE THREAD

**Issue by haloboyvash** [proohit/chrome-reddit-comment-arrow#1]
My comment arrow has been working great for a while, now within the past few weeks the arrow is greyed out and I can no longer jump to the next comment.

**Comment by proohit** [comment]
Hey, thanks for your feedback. Will have a look as soon as possible!

**Comment by proohit** [comment]
Yeah, so reddit changed their comment structure back to the old one. Don't know what they're doing and why they're constantly swapping their implementation. Should be fixed with version 1.0.14 and be available in the store soon

**Comment by haloboyvash** [comment]
Thank you so much for fixing this, it's the greatest addition to desktop reddit browsing there is!
