### ISSUE TITLE
Arrow grey out on old.reddit

### ISSUE THREAD

**Issue by Blahx** [proohit/chrome-reddit-comment-arrow#4]
![Screenshot 2024-11-16](https://github.com/user-attachments/assets/7f65e5a9-056e-497d-aa66-f33c6a3478be)

Grey out and unusable on old.reddit

**Comment by proohit** [comment]
Hey @Blahx and thanks for your report. What do you mean by "old reddit"? Do you have an URL or something where I can reproduce your issue?

Edit: Wow, I think I'm too young for that :D you mean old.reddit.com right? Will investigate shortly.

**Comment by Blahx** [comment]
Yup, old.reddit.com

**Comment by proohit** [comment]
@Blahx thank you for your contribution. This issue will be fixed in version 1.3.1.
